Attempt to fix compilation warnings in #4
User jukebox017 reports errors (warnings which are treated as errors
due to our use of -Werror) such as the following when building Snipes:

Snipes.cpp: In function ‘int main(int, char**)’:
Snipes.cpp:2200:65: error: ignoring return value of ‘size_t fread(void*, size_t, size_t, FILE*)’, declared with attribute warn_unused_result [-Werror=unused-result]
    fread(&random_seed_lo, sizeof(random_seed_lo), 1, replayFile);

I couldn't reproduce these warnings, so these fixes are going by the
provided error log.